[package]
edition = "2024"
name = "pico_rust"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
cortex-m = { version = "0.7", optional = true }
cortex-m-rt = { version = "0.7", optional = true }

embassy-executor = { version = "0.9", optional = true, features = [
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
] }
embassy-net = { version = "0.7", optional = true, features = [
  "defmt",
  "proto-ipv4",
  "medium-ethernet",
  "dhcpv4",          # because you're calling Config::dhcpv4(...)
  "tcp", "udp",      # if you’ll open sockets
  "dns"              # if you’ll resolve hostnames
] }
embassy-rp = { version = "0.8", optional = true, features = [
    "defmt",
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
    # Use the correct RP2350 variant. Pico 2 / 2 W boards ship with 'B' silicon.
    # If your board is 'A' silicon, switch this feature back to "rp235xa".
    "rp235xb",
    "binary-info",
] }
embassy-time = { version = "0.5", features = [
    "defmt",
    "defmt-timestamp-uptime",
] }
embassy-usb = "0.5"
embassy-usb-logger = { version = "0.5", optional = true }
usbd-hid = "0.8.1"

defmt = { version = "1", optional = true }
defmt-rtt = { version = "1", optional = true }
panic-probe = { version = "1", optional = true, features = ["print-defmt"] }

static_cell = "2.1.0"
log = "0.4"
embassy-sync = "0.7"
embassy-futures = "0.1"
heapless = "0.9"
portable-atomic = { version = "1", features = ["critical-section"] }

cyw43 = { version = "0.5", optional = true, features = [
    "defmt",
    "firmware-logs",
] }
cyw43-pio = { version = "0.8", optional = true, features = [
    "defmt",
] }
leasehund = { version = "0.2", optional = true }


[features]
psram = []
default = ["firmware"]
firmware = [
  "cortex-m",
  "cortex-m-rt",
  "embassy-executor",
  "embassy-net",
  "embassy-rp",
  "embassy-usb-logger",
  "defmt",
  "defmt-rtt",
  "panic-probe",
  "cyw43",
  "cyw43-pio",
  "leasehund",
]
