[package]
name = "host-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bytes = "1"
clap = { version = "4.5", features = ["derive"] }
hostname = "0.4.2"
serialport = "4.7"
tokio = { version = "1.37", features = ["fs", "io-util", "macros", "process", "rt-multi-thread", "sync", "time"] }
tokio-serial = "5.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
test-port-fd = []

[dev-dependencies]
libc = "0.2"
