[package]
name = "keyboard-core"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
bytecode-constants = { path = "../bytecode-constants" }

[features]
default = []
alloc = []
std = ["alloc"]
layout_win_en_gb = []
layout_win_pt_br = []
layout_win_de_de = []
layout_mac_en_gb = []
layout_mac_pt_br = []
layout_mac_de_de = []
