//! Compile built-in DSL scripts into firmware payload bytecode.

use super::*;
use core::fmt::Write as _;

pub fn register_reruns(cfg: &Config) {
    let base = cfg.repo_root.join("crates/builtin-scripts");
    cargo::rerun_if_changed(base.join("Cargo.toml"));
    cargo::rerun_if_changed(base.join("src"));
}

pub fn prepare(cfg: &Config) -> Result<()> {
    let mut buf = String::new();
    writeln!(
        buf,
        "// @generated by build-support. Do not edit by hand.\nstatic PAYLOADS: &[Payload] = &["
    )
    .ok();

    for script in builtin_scripts::all() {
        let bytecode = compile_script(script)?;
        if bytecode.len() > bytecode_constants::MAX_BYTECODE {
            bail!(
                "payload {} bytecode is {} bytes (max {})",
                script.id,
                bytecode.len(),
                bytecode_constants::MAX_BYTECODE
            );
        }
        writeln!(buf, "    Payload {{").ok();
        writeln!(buf, "        name: {:?},", script.name).ok();
        writeln!(buf, "        detail: {:?},", script.description).ok();
        writeln!(buf, "        dsl: {:?},", script.dsl).ok();
        buf.push_str("        program: &[\n");
        fmt_bytes(&mut buf, &bytecode);
        buf.push_str("        ],\n");
        buf.push_str("    },\n");
    }

    buf.push_str("];\n");
    fs::write(cfg.out_dir.join("payloads_gen.rs"), buf)
        .context("write payloads_gen.rs into OUT_DIR")?;
    Ok(())
}

fn compile_script(script: &builtin_scripts::BuiltinScript) -> Result<Vec<u8>> {
    struct Provider;
    impl dsl_core::ScriptProvider for Provider {
        fn get<'a>(&'a self, id: &'a str) -> Option<&'a str> {
            builtin_scripts::lookup(id).map(|s| s as &str)
        }
    }

    let program = dsl_core::compile_and_link_with_required_layout(script.dsl, &Provider)
        .map_err(|e| compile_err("compile", script.id, e))?;
    let flat = dsl_core::lower_to_flat(&program).map_err(|e| compile_err("lower", script.id, e))?;
    let bytes = dsl_core::bytecode::encode(&flat).map_err(|_| {
        anyhow::anyhow!(
            "payload {} encode error: program exceeds maximum length",
            script.id
        )
    })?;
    Ok(bytes)
}

fn compile_err(stage: &str, id: &str, err: dsl_core::CompileError) -> anyhow::Error {
    anyhow::anyhow!(
        "payload {id} {stage} error: {} (line {})",
        err.code,
        err.span.line
    )
}

fn fmt_bytes(out: &mut String, bytes: &[u8]) {
    const PER_LINE: usize = 12;
    for chunk in bytes.chunks(PER_LINE) {
        out.push_str("            ");
        for (idx, b) in chunk.iter().enumerate() {
            if idx > 0 {
                out.push_str(", ");
            }
            let _ = write!(out, "0x{:02x}", b);
        }
        out.push_str(",\n");
    }
}
