//! Serving compiled WebAssembly frontend assets.

use crate::http::util::BytesWithType;
use picoserve::response::Response;

mod frontend_static {
    // Generated by build.rs into OUT_DIR
    include!(concat!(env!("OUT_DIR"), "/frontend_static.rs"));
}

pub(crate) async fn route_frontend_index() -> impl picoserve::response::IntoResponse {
    log::debug!("http: serve index.html");
    Response::ok(BytesWithType {
        ty: "text/html; charset=utf-8",
        data: frontend_static::INDEX_HTML.as_bytes(),
    })
}

pub(crate) async fn route_frontend_js() -> impl picoserve::response::IntoResponse {
    log::debug!(
        "http: serve app.js ({} bytes)",
        frontend_static::APP_JS.len()
    );
    Response::ok(BytesWithType {
        ty: "application/javascript",
        data: frontend_static::APP_JS,
    })
}

pub(crate) async fn route_frontend_wasm() -> impl picoserve::response::IntoResponse {
    log::debug!(
        "http: serve app.wasm ({} bytes)",
        frontend_static::APP_WASM.len()
    );
    Response::ok(BytesWithType {
        ty: "application/wasm",
        data: frontend_static::APP_WASM,
    })
}

pub(crate) async fn route_frontend_style() -> impl picoserve::response::IntoResponse {
    log::debug!(
        "http: serve style.css ({} bytes)",
        frontend_static::STYLE_CSS.as_bytes().len()
    );
    Response::ok(BytesWithType {
        ty: "text/css; charset=utf-8",
        data: frontend_static::STYLE_CSS.as_bytes(),
    })
}
